image: maven:3.3.9-jdk-8

stages:
  - build
  - checkstyle
  
build:
  stage: build
  script: 
    - "mvn install -B"
    - "mvn test"
    - "COVERAGE=$(xmllint --html --xpath '//table[@id=\"coveragetable\"]/tfoot//td[@class=\"ctr2\"][1]/text()' target/site/jacoco/index.html)"
    - 'echo "Coverage: $COVERAGE"

checkstyle:
  stage: checkstyle
  script:
    - "mvn site"
  artifacts:
