image: maven:3.3.9-jdk-8

stages:
  - build
  - test
  
build:
  stage: build
  script: 
    - "mvn install -B"
    - "cat target/site/jacoco/index.html"

checkstyle:
  stage: checkstyle
  script:
    - "mvn site"
  artifacts:
