image: maven:3.3.9-jdk-8

stages:
  - build
  - test
  - checkstyle

build:
  stage: build
  script:
    - mvn install -B

java:
  stage: test
  script:
    - mvn test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

checkstyle:
  stage: checkstyle
  script:
    - mvn site
    - mkdir public
    - mv target/site/checkstyle.html public
    - mv target/site/images public
    - mv target/site/css public
  artifacts:
    paths:
      - public