image: java:latest
stages:
    - prebuild
    - build
    - execute
    
prebuild:
    stage: prebuild
    script:
    - $MAVEN_HOME/bin/mvn clean
    
build:
      stage: build
      script: "mvn install -B"