image: maven:3.3.9-jdk-8

stages:
  - build
  - test
  - checkstyle

build:
  stage: build
  script: "mvn install -B"

test:
  stage: test
  script:
    - "mvn clean verify"
  artifacts:
    paths:
      - target/site/jacoco/

checkstyle:
  stage: checkstyle
  script:
    - "mvn site"
  artifacts:
