image: maven:3.3.9-jdk-8

stages:
  - build
  - checkstyle
  
build:
  stage: build
  script: 
    - "mvn install -B"
    - "mvn test"
    - "mvn jacoco:report"
    - "echo \"$(cat target/site/jacoco/testcoverage.txt)% covered\""
checkstyle:
  stage: checkstyle
  script:
    - "mvn site"
  artifacts:
