image: maven:3.3.9-jdk-8

stages:
  - build
  - checkstyle
  
build:
  stage: build
  script: 
    - "mvn install -B"
    - "mvn verify"
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml